timezone: America/Denver
# Dependencies
markdown:       redcarpet
redcarpet:
    extensions: ['smart']

highlighter:         pygments
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            thin line between info and data
tagline:          r.v. vincelli pages
url:              http://rvvincelli.github.io/
paginate:         5
baseurl:          /

# About/contact
author:
  name:           Riccardo V. Vincelli
  email:          ReimOne@Gmail.com

