name: Hank Quinlan, Horrible Cop
markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md
highlighter: pygments
redcarpet:
 extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
permalink: /blog/:year/:month/:day/:title
