timezone: America/Denver
# Dependencies
markdown:       redcarpet
redcarpet:
    extensions: ['smart', 'tables']

highlighter:         pygments
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            thin line between info and data
tagline:          r.v. vincelli pages
url:              http://rvvincelli.github.io/
paginate:         5
baseurl:          /

# About/contact
author:
  name:           Riccardo V. Vincelli
  email:          ReimOne@Gmail.com
  github: 	  rvvincelli
  twitter: 	  rvvincelli
  linkedin: 	  riccardo-vincenzo-vincelli/60/791/24b
  facebook: 	  riccardo.vincelli
  scribd: 	  riccardo_vincelli
  youtube: 	  reimuno


